language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 050fdd9f-21b5-491b-b938-437a0096daad
